.TH KAGI-VOLUME-QEMU-SCSI 1 "September 2026" "Kagi 0.38.0" "User Commands"
.SH NAME
kagi-volume-qemu-scsi \- generate QEMU arguments for virtio-SCSI or virtual SAS presentation
.SH SYNOPSIS
.B kagi-volume-qemu-scsi
virtio-scsi|sas HOST PORT [ARGS]
.SH DESCRIPTION
Builds a QEMU device/backend command line that uses Kagi block storage while presenting the guest with a paravirtualized SCSI disk or an emulated SAS/SCSI controller.
.SH SEE ALSO
kagi-volume-nbd(1), kagi-volume-libvirt-scsi(1), qemu-system-x86_64(1)
